export const typesUI = {
    INIT_CELLS:             'INIT_CELLS',
    FETCH_WINS_BEGIN:       'FETCH_WINS_BEGIN',
    FETCH_WINS_SUCESS:      'FETCH_WINS_SUCESS',
    FETCH_WINS_FAILURE:     'FETCH_WINS_FAILURE',
    FILL_CELLS:             'FILL_CELLS',
    CELL_TOGGLE:            'CELL_TOGGLE',
    ALERT_CLOSE:            'ALERT_CLOSE',
    SUBMIT_BLOCKS:          'SUBMIT_BLOCKS',
    GET_TOTAL_POINTS:       'GET_TOTAL_POINTS',
    OPEN_END_GAME_MODAL:    'OPEN_END_GAME_MODAL',
    CLOSE_END_GAME_MODAL:   'CLOSE_END_GAME_MODAL',
    START_NEW_GAME:         'START_NEW_GAME',

};
